# Generated by Django 5.0.7 on 2024-07-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentg.dept_category'),
        ),
    ]
