# Generated by Django 5.0.7 on 2024-07-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redressal', '0004_alter_department_id_alter_institute_id_and_more'),
        ('studentg', '0002_alter_grievance_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'University'), (2, 'Institute'), (3, 'Department')]),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='redressal.subcategory'),
            preserve_default=False,
        ),
    ]
