# Generated by Django 5.0.7 on 2024-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_departmentmember_id_alter_institutemember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('ADM', 'Admin'), ('STU', 'Student'), ('UNI', 'University Member'), ('INS', 'Institute Member'), ('DEP', 'Department Member'), ('UNI_H', 'University Head'), ('INS_H', 'Institute Head'), ('DEP_H', 'Department Head')], max_length=5, null=True),
        ),
    ]
