# Generated by Django 5.0.7 on 2024-07-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='redressal_body',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
    ]
