# Generated by Django 5.0.7 on 2024-07-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_student_redressal_body_remove_student_rollno'),
        ('redressal', '0004_alter_department_id_alter_institute_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='redressal_body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='redressal.redressalbody'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
