# Generated by Django 5.0.7 on 2024-07-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redressal', '0004_alter_department_id_alter_institute_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=255)),
                ('sub_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.redressalbody')),
            ],
        ),
    ]
